# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Ham-APRS-FAP
version:      1.11
version_from: FAP.pm
installdirs:  site
requires:
    Date::Calc:                    5
    Math::Trig:                    1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
